# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Loom is not yet fully compatible with configuration cache
org.gradle.configuration-cache=false
# Fabric Properties (https://fabricmc.net/develop)
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.17.21

# Mod Properties
version=1.1.0
group=dev.anglewatcher

# Dependencies
fabric_api_version=0.160.0+26.2
modmenu_version=20.0.2
yacl_version=3.9.6+26.2-fabric
